//
// Created by max on 11/21/25.
//

#ifndef ETHERNET_PTP_CONFIG_H
#define ETHERNET_PTP_CONFIG_H

#define CONFIG_SAMPLING_RATE 48000
#define CONFIG_ENTITY_CAPABILITIES 0x0000C508
#define CONFIG_TALKER_STREAM_SOURCES 1
#define CONFIG_TALKER_CAPABILITIES 0x4001
#define CONFIG_LISTENER_STREAM_SINKS 1
#define CONFIG_LISTENER_CAPABILITIES 0x4001

#endif //ETHERNET_PTP_CONFIG_H
